# edit from https://github.com/craigcitro/r-travis/blob/master/sample.travis.yml
# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_r devtools
  - ./travis-tool.sh install_github klutometis/roxygen

install:
  - ./travis-tool.sh install_github jianan/simcross
  - ./travis-tool.sh install_bioc_deps
  - ./travis-tool.sh install_github jianan/DOQTL
  - make -k prebuild

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

# use travis to auto-make: generate Rd and RcppExports
after_success:
  - git config --global user.email "jiant17@gmail.com"
  - git config --global user.name "Jianan Tian"
  - ./.travis.deploy.sh -s source -d master -c 'make -k prebuild'

env:
  global:
    secure: "Ip3FREnjN059+vXg4IeON+E/az+cuKrP/NjRR72cUoYeXPKnpa6V4//T62Dg5YKmKhQe4HdVQDamMmlqn4e7Bc/jBfelj4/hGY6MQOlESpYKtGB8VRZKQrHoKXhnfEnNRYVwM78XVLFXu5zD4OnuKFIg8lXu5ssk4kHddN6Okfw="

## exclude the deploy branch from build on travis-ci
branches:
  except:
    - master
